version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive

  settings:
    revive:
      rules:
        - name: blank-imports
        - name: exported
        - name: unreachable-code
        - name: unused-parameter

formatters:
  enable:
    - gofumpt

  settings:
    gofumpt:
      extra-rules: true

output:
  sort-order:
    - file
